discord:
    token: ''
    client_id: ''
    client_secret: ''
    # Server ID des Servers, auf dem der Bot aktiv ist (wird für OAuth2 benötigt)
    server_id: ''
    # Vorzugsweise ein permanenter Link, wird Nutzern angeboten, die noch nicht auf dem Discord sind
    invite_link: 'https://discord.gg/XXX'
    # Prefix, der vor Commands geschrieben wird
    prefix: '.'
    # Die Channel ID des Channels, in den die Willkommens-Nachrichten geschickt werden
    lobby_channel_id: ''
    # Hier kann die Willkommens-Nachricht personalisiert werden
    welcome_message: '**Hey, //USER// 👋**\n **Willkommen auf dem Discord des Programmier-Wettbewerbs.**\n Schön, dass du da bist!'

api:
    # Keine Adresse = API läuft auf 0.0.0.0
    address_and_port: ':5000'